eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8765
spring:
  application:
    name: service-feign



logging:
  level:
    root: info
    org:
      springframework: info
    com:
      netflix: debug

feign:
  hystrix:
    enabled: true