eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8769
spring:
  application:
    name: service-zuul
  cloud:
      loadbalancer:
        retry:
          enabled: true

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
    xx:
      path: /xx/**
      serviceId: service-hi
# 开启重试
  retryable: true

# 请求连接的超时时间
ribbon:
  connectTimeout: 2000
  # 请求处理的超时时间
  readTimeout: 5000
  # 对当前实例的重试次数
  maxAutoRetries: 1
  # 切换实例的重试次数
  maxAutoRetriesNextServer: 3
  # 对所有操作请求都进行重试
  okToRetryOnAllOperations: true

# hystrix的超时时间必须大于ribbon的超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000