server:
  port: 8762

spring:
  application:
    name: service-hi
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: info
    org:
      springframework: info
    com:
      netflix: debug

